server:
  port: 8080

spring:
  application:
    name: "spring-school"

  datasource:
    url: jdbc:mysql://localhost:3306/schooldb
    username: root
    password: July723!

  jpa:
    show-sql: true

  sql:
    init:
      mode: always

  thymeleaf:
    cache: false

build:
  version: "1.0"
